language: cpp

sudo: required

services:
  - docker

compiler:
  - clang


before_install:
  - docker pull tkzdockerid/nut-testenv:clang-10-0-C

script:
  - docker run -it tkzdockerid/nut-testenv:clang-10-0-C /bin/bash test_nut.sh $TRAVIS_BRANCH
